language: java
jdk: openjdk8
dist: trusty
addons:
  apt:
    packages:
      - debhelper
      - make
      - fakeroot
before_cache:
  - rm -f $TRAVIS_BUILD_DIR/.citemp/caches/modules-2/modules-2.lock
  - rm -rf $TRAVIS_BUILD_DIR/.citemp/caches/*/plugin-resolution/
cache:
  directories:
    - $TRAVIS_BUILD_DIR/.citemp/caches/
    - $TRAVIS_BUILD_DIR/.citemp/wrapper

script:
  - ./gradlew --quiet -g .citemp --no-daemon distTar
  - make -f Makefile.deb all

install: true
deploy:
  provider: releases
  api_key:
    secure: nQCB6Rqmvi1/K79xohIoeJZXoiMiaCm0Hy6yBa/wuTEMThJP6EU+zfFVnmVw3jhE2Z5yzLcazNrIDEzWbmn2i4TtiLxD9dleqPfyiRLi2fzNNUHt3xg3q61ceqoRMXQVPooNwteEwzaNOsuHt7yGMSlYg9vaBy1RELXyWMa9V6NHf73ukR8i6lkQB4pPXHL/pCjdvhwZ7CuN1ULJQ6v2OcPEwNQb13pV9eWMY+anW3ku71neK20cDIzjjDEDuCMluYE+LCDCb5F/ShcYvRolGydDm4JQEjwrh+ldaPmQzhTaVCBNjAswcwjV9m45A9RDJp8dTHk+4lCmdy0r3ifqOcudb+UQjs+vZmWoS3ursUO1oGorzk5rZ87glVgnj18t+bBWeCF7hTXHEyWlRjkCLx5rZqgtZIRHMiZ3SjaWGHdZSKvohAInCtLhVjaA3uFgLjsieU+GBmd9+yHBiG+lTnfR2OxTaMlnipqySuSNbAmEzjnk/WaNzVhh1gdQ97JuvhcPvfy3MeV+ZS/lbtmWLaLqAwDOmC+EKLCaHBtUqGEI7XG9zvyBeiWqTlTyljyYEq1bdiUvGyYTQz8pJus2tq7E95sG1JWhdLAF7JwmqfVtKJlSLlFt8tdzPVnxHKeEx+DBKbIKGZJ+IFtoFjHosnEhzvSXQqRKUzeHyAY5kLw=
  skip_cleanup: true
  file_glob: true
  file:
    - build/distributions/portal-resource-server-*.tar.gz
    - portal-resource-server_*_all.deb
  draft: false
  overwrite: true
  on:
    tags: true
