name: Build & Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Work around https://github.com/actions/checkout/issues/290
      - run: git fetch --force --tags

      - uses: actions/cache@v2
        with:
          path: |
            .citemp/caches
            .citemp/wrapper
          key: gradle-cache
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - run: sudo apt-get -y install debhelper make fakeroot
      - run: ./gradlew --quiet -g .citemp --no-daemon distTar
      - run: make -f Makefile.deb all

      - name: stage distribution files
        run: |
          mkdir -p dist
          cp portal-resource-server_*_all.deb dist/
          cp build/distributions/portal-resource-server-*.tar.gz dist/

      - uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist/*

  deploy:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-artifacts
          path: dist

      - name: Sign packages
        run: |
          sudo apt-get -y install dpkg-sig
          printf '%s' "$RCC_PACKAGE_SIGNING_KEY" | gpg --import --batch
          dpkg-sig -k $RCC_PACKAGE_SIGNING_KEY_ID -s builder dist/*.deb

          for i in dist/*; do
            sha256sum "$i" > "$i.sha256"
          done
        env:
          RCC_PACKAGE_SIGNING_KEY: ${{ secrets.RCC_PACKAGE_SIGNING_KEY }}
          RCC_PACKAGE_SIGNING_KEY_ID: ${{ secrets.RCC_PACKAGE_SIGNING_KEY_ID }}

      # - name: Push packages to packages.rcc.uq.edu.au
      #   run: |
      #     mkdir -p ~/.ssh && chmod 0700 ~/.ssh
      #     printf '%s' "$RCC_PACKAGE_KNOWN_HOSTS" > ~/.ssh/known_hosts
      #     printf '%s' "$RCC_PACKAGE_SSH_KEY" > deploy
      #     chmod 0600 deploy

      #     sftp -i deploy gh-actions@packages.rcc.uq.edu.au <<EOF
      #       put dist/*.deb /ubuntu/pool/main/portal-resource-server
      #     EOF
      #   env:
      #     RCC_PACKAGE_SSH_KEY: ${{ secrets.RCC_PACKAGE_SSH_KEY }}
      #     RCC_PACKAGE_KNOWN_HOSTS: ${{ secrets.RCC_PACKAGE_KNOWN_HOSTS }}

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
