name: Build & Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Work around https://github.com/actions/checkout/issues/290
      - run: git fetch --force --tags

      - uses: actions/cache@v2
        with:
          path: |
            .citemp/caches
            .citemp/wrapper
          key: gradle-cache
      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - run: sudo apt-get -y install debhelper make fakeroot
      - run: ./gradlew --quiet -g .citemp --no-daemon distTar
      - run: make -f Makefile.deb all

      - name: stage distribution files
        run: |
          mkdir -p dist
          cp portal-resource-server_*_all.deb dist/
          cp build/distributions/portal-resource-server-*.tar.gz dist/

          for i in dist/*.deb dist/*.tar.*; do
            sha256sum $i > $i.sha256
          done

      - uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: dist/*

  deploy:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-artifacts
          path: dist
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
